import io
import json

import pytest

import overseer_server as server


class FakeThread:
    started = []

    def __init__(self, target=None, args=(), daemon=None):
        self.target, self.args = target, args

    def start(self):
        FakeThread.started.append((self.target, self.args))


@pytest.fixture(autouse=True)
def fresh_state(monkeypatch):
    FakeThread.started = []
    monkeypatch.setattr(server.threading, "Thread", FakeThread)
    monkeypatch.setitem(server.STATE, "status", "idle")
    monkeypatch.setitem(server.STATE, "opportunities", [{"topic": "a"}, {"topic": "b"}])


def request(method, path, body=None, headers=None):
    payload = json.dumps(body).encode() if body is not None else b""
    base = {"Host": "localhost:3000"}
    if body is not None:
        base.update({"Content-Type": "application/json", "Content-Length": str(len(payload))})
    base.update(headers or {})

    handler = server.Handler.__new__(server.Handler)
    handler.command, handler.path = method, path
    handler.request_version, handler.requestline = "HTTP/1.1", f"{method} {path} HTTP/1.1"
    handler.client_address = ("127.0.0.1", 50000)
    handler.headers = base
    handler.rfile, handler.wfile = io.BytesIO(payload), io.BytesIO()
    getattr(handler, f"do_{method}")()

    raw = handler.wfile.getvalue().decode()
    head, _, body_text = raw.partition("\r\n\r\n")
    status = int(head.split(" ")[1])
    try:
        return status, json.loads(body_text)
    except json.JSONDecodeError:
        return status, body_text


def test_run_starts_a_job_and_refuses_a_second():
    status, body = request("POST", "/api/run", {"channels": ["https://youtube.com/@a"]})
    assert status == 200 and body["ok"]
    assert FakeThread.started[0] == (server.run_research, (["https://youtube.com/@a"], "", "", ""))

    status, body = request("POST", "/api/run", {"channels": ["https://youtube.com/@a"]})
    assert status == 409
    assert len(FakeThread.started) == 1


def test_run_accepts_a_prompt_on_its_own():
    status, body = request("POST", "/api/run", {
        "prompt": "  A calm documentary on Japanese trains  ",
        "format": "documentary",
        "length": "8-15",
    })
    assert status == 200
    assert FakeThread.started == [
        (server.run_research, ([], "A calm documentary on Japanese trains", "documentary", "8-15")),
    ]


@pytest.mark.parametrize("body", [
    {},
    {"prompt": "   ", "channels": []},
    {"prompt": "x" * 2001},
    {"prompt": "trains", "format": "musical"},
    {"prompt": "trains", "length": "forever"},
])
def test_run_rejects_bad_requests(body):
    status, _ = request("POST", "/api/run", body)
    assert status == 400
    assert FakeThread.started == []


def test_simple_cross_site_request_is_refused():
    status, _ = request(
        "POST", "/api/run", {"channels": ["x"]},
        headers={"Content-Type": "text/plain"},
    )
    assert status == 415
    assert FakeThread.started == []


def test_foreign_origin_is_refused():
    status, _ = request("POST", "/api/run", {"channels": ["x"]}, headers={"Origin": "https://evil.example"})
    assert status == 403


def test_foreign_host_header_is_refused():
    status, _ = request("GET", "/api/status", headers={"Host": "evil.example:3000"})
    assert status == 403


def test_bad_content_length_is_rejected():
    status, _ = request("POST", "/api/run", {"channels": ["x"]}, headers={"Content-Length": "abc"})
    assert status == 400


def test_produce_validates_the_index():
    assert request("POST", "/api/produce", {"opportunity": 5})[0] == 400
    assert request("POST", "/api/produce", {"opportunity": True})[0] == 400

    status, body = request("POST", "/api/produce", {"opportunity": 1})
    assert status == 200
    assert FakeThread.started == [(server.run_production, (1,))]


def test_restore_latest_shows_last_run_and_production(config, monkeypatch):
    from fakes import FakeResearcher, OfflineLLM

    from src.pipeline import PipelineOptions, produce_from_run, run_pipeline

    run_pipeline(config, PipelineOptions(channels=["@a"]), llm=OfflineLLM(), researcher=FakeResearcher())
    produce_from_run(config, 0, llm=OfflineLLM())
    monkeypatch.setattr(server, "STATE", dict(server.STATE))

    server.restore_latest()

    state = server.snapshot_state()
    assert state["opportunities"] and state["opportunities"][0]["tier"] in {"validated", "hypothesis"}
    production = state["production"]
    assert production["has_brief"] and not production["has_script"]
    assert production["fallbacks"] == ["brief", "script", "thumbnails"]
    assert "Brief generated by the model" in production["failed_checks"]
    assert production["sections"] == [] and production["checks"]
    assert production["run_path"] == f"outputs/runs/{production['run_id']}"
    assert state["memory"]["videos_analyzed"] == 0
    assert state["memory"]["top_topics"] == []


def test_status_returns_a_snapshot():
    status, body = request("GET", "/api/status")
    assert status == 200
    assert body["opportunities"] == [{"topic": "a"}, {"topic": "b"}]
    assert "warnings" in body and "research_mode" not in body
