from __future__ import annotations

from typing import Any

from .models import ChannelConfig

MAX_THUMBNAIL_WORDS = 5


class QAAgent:
    """Turn production output into a review checklist and a publish gate.

    Every claim the brief or script flagged must be marked verified, with a
    source, before `main.py --record-published` will accept the video. The
    automated checks catch structural problems; they do not judge quality.
    """

    def __init__(self, config: ChannelConfig) -> None:
        self.config = config

    def review(
        self,
        brief: dict[str, Any],
        script: dict[str, Any] | None = None,
        thumbnail: dict[str, Any] | None = None,
        target_minutes: float | None = None,
    ) -> dict[str, Any]:
        script = script or {}
        thumbnail = thumbnail or {}

        claims: list[str] = []
        for claim in [*brief.get("claims_to_verify", []), *script.get("fact_check_queue", [])]:
            text = str(claim).strip()
            if text and text not in claims:
                claims.append(text)

        checks = [
            self._check(
                "Brief generated by the model",
                "fallback_reason" not in brief,
                brief.get("fallback_reason", ""),
            ),
            self._check(
                "Brief has a working title and hook",
                bool(brief.get("working_title")) and bool(brief.get("opening_hook")),
                "",
            ),
        ]

        if script:
            sections = script.get("sections", [])
            checks.append(self._check(
                "Script generated by the model",
                "fallback_reason" not in script,
                script.get("fallback_reason", ""),
            ))
            checks.append(self._check(
                "Script has sections with narration",
                bool(sections) and all(str(s.get("narration", "")).strip() for s in sections),
                f"{len(sections)} section(s)",
            ))
            target = target_minutes or self.config.content.get("target_minutes")
            minutes = script.get("estimated_minutes")
            if target and isinstance(minutes, (int, float)):
                checks.append(self._check(
                    "Script length is within 50% of the target",
                    abs(minutes - target) <= target * 0.5,
                    f"{minutes} min estimated, {target} min target",
                ))

        if thumbnail:
            long_texts = [
                concept.get("text", "")
                for concept in thumbnail.get("concepts", [])
                if len(str(concept.get("text", "")).split()) > MAX_THUMBNAIL_WORDS
            ]
            checks.append(self._check(
                f"Thumbnail text is {MAX_THUMBNAIL_WORDS} words or fewer",
                not long_texts,
                "; ".join(long_texts),
            ))

        failed = [check["name"] for check in checks if not check["passed"]]
        return {
            "status": "needs_review",
            "publish_ready": False,
            "failed_checks": failed,
            "checks": checks,
            "claims": [
                {"claim": claim, "verified": False, "source": ""}
                for claim in claims
            ],
            "how_to_clear": (
                "Edit this file: for each claim set verified to true and add a "
                "source, or remove the claim from the script. Failed checks need "
                "the script or brief fixed and QA re-run. Publishing is recorded "
                "with `python main.py --record-published VIDEO_ID`, which refuses "
                "while any claim is unverified."
            ),
        }

    @staticmethod
    def _check(name: str, passed: bool, detail: str) -> dict[str, Any]:
        return {"name": name, "passed": bool(passed), "detail": detail}


def unresolved_claims(qa_report: dict[str, Any]) -> list[str]:
    """Claims that are not yet marked verified with a source."""
    return [
        str(item.get("claim", ""))
        for item in qa_report.get("claims", [])
        if not (item.get("verified") and str(item.get("source", "")).strip())
    ]
